name: studio_partner_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-261.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  fpdart: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  pinput: ^5.0.0
  password_strength_indicator: ^1.0.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  flutter_inset_box_shadow: ^1.0.8

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/placeholders/
    - assets/animations/
    - assets/icons/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
